# Site Settings
title: Blog | MinhThanh
email: sannguyen449@gmail.com
description: My first time!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.minhthanh1412.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Minh Thanh
user_description: My first time!
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: minhthanh1412
facebook_username: nguyenvan.sang.96742277


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
